on:
  workflow_call:
    inputs:
      ANSIBLE_ACTION:
        type: string
        default: "check_diff"
      ANSIBLE_CHDIR:
        type: string
        default: "terraform/ansible/jumpbox"
      AWS_REGION:
        type: string
        default: "us-east-1"
      AWS_PROFILE_NAME:
        type: string
        default: "awsdevopskats"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ANSIBLE_SSH_PRIVATE_KEY:
        required: true
      ANSIBLE_SSH_USER:
        required: true

jobs:
  jumpbox:
    runs-on: ubuntu-latest
    steps:
      - name: Add profile credentials to ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile ${{ inputs.AWS_PROFILE_NAME }}
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile ${{ inputs.AWS_PROFILE_NAME }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install python boto3, ansible
        run: |
          pip install boto3 requests ansible==2.9.6 ansible-lint==4.2.0
          ansible-galaxy collection install community.aws
      - name: set ansible config secrets
        env:
          SSH_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -pv ${{ inputs.ANSIBLE_CHDIR }}/.ssh
          echo "$SSH_KEY" >  ${{ inputs.ANSIBLE_CHDIR }}/.ssh/id_rsa
          chmod 600  ${{ inputs.ANSIBLE_CHDIR }}/.ssh/id_rsa
      - name: Lint Ansible Playbook
        run: |
          ansible-lint -x 403 ${{ inputs.ANSIBLE_CHDIR }}/tasks.yml
      - name: List host ready for Ansible Playbook
        run: |
          ansible-inventory --graph -i ${{ inputs.ANSIBLE_CHDIR }}/inventory_aws_ec2.yml
      - name: Run ansible playbook check diff
        if: inputs.ANSIBLE_ACTION == 'check_diff'
        run: |
          ansible-playbook ${{ inputs.ANSIBLE_CHDIR }}/tasks.yml -u ${{ secrets.ANSIBLE_SSH_USER }} -i ${{ inputs.ANSIBLE_CHDIR }}/inventory_aws_ec2.yml --private-key ${{ inputs.ANSIBLE_CHDIR }}/.ssh/id_rsa --check --diff -vv
      - name: Run ansible playbook apply
        if: inputs.ANSIBLE_ACTION == 'apply'
        run: |
          ansible-playbook ${{ inputs.ANSIBLE_CHDIR }}/tasks.yml -u ${{ secrets.ANSIBLE_SSH_USER }} -i ${{ inputs.ANSIBLE_CHDIR }}/inventory_aws_ec2.yml --private-key ${{ inputs.ANSIBLE_CHDIR }}/.ssh/id_rsa -vv