on:
  workflow_call:
    inputs:
      test_url:
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Selenium Test
        uses: addnab/docker-run-action@v3
        env:
          TEST_URL: ${{ inputs.test_url }}
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          image: stuartshay/azuredevopskats-selenium:latest
          options: -v /tmp/assets:/tmp/assets -v /dev/shm:/dev/shm -e TEST_URL
          run: |
            echo "TEST URL: $TEST_URL"
            python3 selenium_screenshot.py $TEST_URL /tmp/assets/devops.png "1000" "500" "//body" "//target"
            ls -al /tmp/assets

      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: |
            /tmp/assets

      - name: Download a test artifact
        uses: actions/download-artifact@v4
        with:
          name: test-screenshots
